"""add cqrs projection, processed_event, reconciliation_check

Revision ID: 42953ec2b284
Revises: d866238bb077
Create Date: 2026-06-29 19:48:03.615336

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42953ec2b284'
down_revision = 'd866238bb077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_event',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('reconciliation_check',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('balanced', sa.Boolean(), nullable=False),
    sa.Column('global_drift_cents', sa.BigInteger(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_check_balanced'), 'reconciliation_check', ['balanced'], unique=False)
    op.create_index(op.f('ix_reconciliation_check_checked_at'), 'reconciliation_check', ['checked_at'], unique=False)
    op.create_table('account_balance',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('events_applied', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_balance')
    op.drop_index(op.f('ix_reconciliation_check_checked_at'), table_name='reconciliation_check')
    op.drop_index(op.f('ix_reconciliation_check_balanced'), table_name='reconciliation_check')
    op.drop_table('reconciliation_check')
    op.drop_table('processed_event')
    # ### end Alembic commands ###
