"""add recurring transfer

Revision ID: d866238bb077
Revises: 163577971c58
Create Date: 2026-06-26 18:30:44.415263

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd866238bb077'
down_revision = '163577971c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transfer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_account_id', sa.Uuid(), nullable=False),
    sa.Column('to_account_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_transfer_active'), 'recurring_transfer', ['active'], unique=False)
    op.create_index(op.f('ix_recurring_transfer_from_account_id'), 'recurring_transfer', ['from_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_transfer_from_account_id'), table_name='recurring_transfer')
    op.drop_index(op.f('ix_recurring_transfer_active'), table_name='recurring_transfer')
    op.drop_table('recurring_transfer')
    # ### end Alembic commands ###
